### ISSUE TITLE
Is there the example code to train it with COCO?

### ISSUE THREAD

**Issue by ardeal** [lukemelas/EfficientNet-PyTorch#279]
Hi,

Is there the example code to train EfficientNet with COCO dataset?
what should the label format be in label file?

**Comment by lukemelas** [comment]
Hi, EfficientNet is an image classification model. COCO is usually used for object detection rather than image classification. If you want to do object detection, you may want to look into EfficientDet (note the _Det_, not _Net_). Let me know if this helps. 

I'm going to close this issue, but feel free to reopen it if you have more questions
